# Meta
title: Arunkumar Sampathkumar
email: hi@arunkumar.dev
description: >-
  Arun's blog and portfolio
baseurl: ""
url: "https://www.arunkumar.dev"
author: "@arunkumar_9t2"

disqus:
  shortname: arunkumarsampath-in

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-gist
  - jemoji
  - jekyll-sitemap

permalink: /:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
      comments: true
      navigation_name: Blog
  - scope:
      path: ""
      type: pages
    values:
      is_post: false
      comments: false

# Collections
collections:
  apps:
    title: Android
  os:
    title: Open Source Work
  talks:
    tilte: Speaking

sass:
  style: compact
