# Meta
title: Arunkumar Sampathkumar
email: arunk.beece@gmail.com
description: >-
  Blog and Portfolio
baseurl: ""
url: "https://www.arunkumarsampath.in" 
author: "@arunkumar_9t2"

disqus:
  shortname: arunkumarsampath-in

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-gist
  - jemoji

permalink: /:year/:month/:day/:title

# Defaults
defaults:
  - scope:
      path: ""      
      type: posts
    values:
      is_post: true
      comments: true
      navigation_name: Blog
  - scope:
      path: ""      
      type: pages
    values:
      is_post: false
      comments: false

# Collections
collections:
  android_apps:
    title : Android
  open_source_work:
    title: Open Source Work
    

